[build]
  command = "npm run build"
  publish = "out"

# Remove the plugins section to be sure
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# These redirects will handle your API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200