[build]
  command = "npm run build && npx next export"
  publish = "out"

# Remove the plugins section with @netlify/plugin-nextjs

# Keep the redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200